apiVersion: v1
kind: Service
metadata:
  name: valheim-udp
  namespace: valheim
  annotations:
    metallb.universe.tf/allow-shared-ip: "valheim"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # (opcional) Si quieres IP fija de MetalLB, añade:
  loadBalancerIP: 192.168.1.241   # elige una del pool de MetalLB
  selector:
    app: valheim
  ports:
  - name: game
    port: 2456
    targetPort: 2456
    protocol: UDP
  - name: query
    port: 2457
    targetPort: 2457
    protocol: UDP
  - name: master
    port: 2458
    targetPort: 2458
    protocol: UDP
