apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-immich-backup-nfs
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.1.65
    path: /backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-backup-nfs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeName: pv-immich-backup-nfs
