apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-immich-backup-nfs
spec:
  capacity:
    storage: 2Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 192.168.1.65
    path: /volume1/backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-backup-nfs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: pv-immich-backup-nfs
