apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-ops-quota
  namespace: ai-ops
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 7Gi
    persistentvolumeclaims: "4"