apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path    # en k3s suele usarse local-path
  resources:
    requests:
      storage: 5Gi                # ajusta al tamaño que necesites
