apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.5   
          imagePullPolicy: IfNotPresent
          args: ["start"]
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: postgres-svc.keycloak.svc.cluster.local
            - name: KC_DB_URL_DATABASE
              value: keycloakdb
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_DB_PORT
              value: "5432"
            - name: KC_HTTP_ENABLED
              value: "true"          # para exponer HTTP (Traefik hará TLS si configuras Ingress con TLS)
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_PROXY
              value: edge            # indica que hay un proxy (Traefik) delante
            - name: KC_LOG_LEVEL
              value: INFO
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"    # sin esto, me da un error raro al intentar re-logearme https://github.com/keycloak/keycloak/issues/33330#issuecomment-2740486452
            # Variables de admin:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: KEYCLOAK_ADMIN_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
            # ) emptyDir para temporales: para que el pvc con longhorn no de problemas
            - name: keycloak-tmp
              mountPath: /opt/keycloak/data/tmp
          # livenessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 8080
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   timeoutSeconds: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 8080
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   timeoutSeconds: 1
          #   failureThreshold: 3
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data-pvc
        - name: keycloak-tmp
          emptyDir: {}