apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-immich-library-nfs
spec:
  capacity:
    storage: 4Ti
  volumeMode: Filesystem
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - proto=tcp
    - hard
    - noatime
  nfs:
    server: 192.168.1.65
    path: /volume1/immich-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-nfs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: pv-immich-library-nfs
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-library
#   namespace: immich
# spec:
#   storageClassName: longhorn
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 60Gi
