apiVersion: v1
kind: Pod
metadata:
  name: immich-nfs-test
  namespace: immich
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: alpine:3.20
      command: ["/bin/sh", "-lc"]
      args:
        - |
          id
          ls -lah /data | head
          touch /data/test-write-from-k8s
          mkdir -p /data/test-dir-from-k8s
          echo "ok" > /data/test-dir-from-k8s/file.txt
          ls -lah /data/test-write-from-k8s /data/test-dir-from-k8s/file.txt
          echo "NFS write test OK"
      volumeMounts:
        - name: immich-library
          mountPath: /data
  volumes:
    - name: immich-library
      persistentVolumeClaim:
        claimName: immich-library-nfs