# metallb-ip-pool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: khazadlab-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.240-192.168.1.249
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: khazadlab-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - khazadlab-pool