---
- name: Configurar nodo Ubuntu (K3s + Cert-Manager + ddclient para DuckDNS + Rancher)
  hosts: all
  become: true

  vars:
    # Variables “públicas” o de configuración general:
    netplan_iface: wlp2s0
    netplan_ip: "192.168.1.60/24"
    netplan_gateway: "192.168.1.1"
    netplan_nameservers:
      - "1.1.1.1"
      - "8.8.8.8"
    k3s_version: "v1.28.1+k3s1"

  tasks:
    - name: Cargar variables de entorno desde fichero .env
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/.env"
        name: env_vars
        type: env

    - name: Pasar variables de env_vars a “facts”
      ansible.builtin.set_fact:
        k3s_install_token: "{{ env_vars.K3S_TOKEN }}"
        duckdns_token: "{{ env_vars.DUCKDNS_TOKEN }}"
        duckdns_domain: "{{ env_vars.DUCKDNS_DOMAIN }}"
        wifi_ssid: "{{ env_vars.WIFI_SSID }}"
        wifi_password: "{{ env_vars.WIFI_PASSWORD }}"
        letsencrypt_email: "{{ env_vars.LETSENCRYPT_EMAIL }}"

  roles:
    - common
    - k3s
    - certmanager
    - ddclient
