FROM cm2network/steamcmd:latest

# Trabajamos como root para copiar scripts y configuraciones
USER root
WORKDIR /home/steam

# Copiamos el script de arranque y marcamos permisos
COPY --chown=steam:steam start.sh .
RUN chmod +x start.sh

# Volvemos al usuario steam para seguridad
USER steam

# El ENTRYPOINT lanza start.sh en tiempo de ejecución
ENTRYPOINT ["./start.sh"]
