FROM cm2network/steamcmd:latest

# 1. Crea el usuario "steam" y directorios
RUN useradd -m steam
USER steam
WORKDIR /home/steam

# 2. Descarga el servidor dedicado (Windows)
RUN steamcmd +login anonymous \
    +force_install_dir /home/steam/dm_srv \
    +app_update 2145 validate \
    +quit

# 3. Copia el script de arranque
COPY --chown=steam:steam start.sh .

ENTRYPOINT ["bash", "start.sh"]