apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: andres.cardosoc12@gmail.com
    privateKeySecretRef:
      name: le-staging-secret
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
