apiVersion: v1
kind: Service
metadata:
  name: valheim-svc
  namespace: valheim
spec:
  selector:
    app: valheim
  ports:
  - name: game
    port: 2456
    targetPort: 2456
    protocol: UDP
  - name: query
    port: 2457
    targetPort: 2457
    protocol: UDP
