apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: longhorn-system
type: Opaque
stringData:
  # El “client-secret” que sacaste de Keycloak (client traefik-oauth2)
  client-secret: ${KEYCLOAK_CLIENT_PASSWORD}
  # Una cadena aleatoria de 32 bytes en base64 para cifrar las cookies.
  cookie-secret: ${KEYCLOAK_CLIENT_PASSWORD}