apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-errors
  namespace: longhorn-system
spec:
  errors:
    status:
      - "401"
    service:
      name: oauth2-proxy
      port: 4180
    query: "/oauth2/start?rd=https://longhorn.khazadlab.duckdns.org"
