---
- name: Configuración completa del nodo Ubuntu
  hosts: all
  become: true

  vars:
    # Variables “estáticas” que no son secretas
    netplan_iface: wlp2s0
    netplan_ip: "192.168.1.60/24"
    netplan_gateway: "192.168.1.1"
    netplan_nameservers:
      - "1.1.1.1"
      - "8.8.8.8"
    k3s_version: "v1.28.1+k3s1"
    # IMPORTANTE: no definimos aquí las variables secretas,
    # las cargaremos desde .env más abajo.

  tasks:
    - name: Cargar variables de entorno desde .env
      ansible.builtin.include_vars:
        file: ".env"
        name: env_vars
        type: env

    # Ahora todas las líneas en .env pasan a estar en `env_vars`
    # Por ejemplo: env_vars.K3S_TOKEN, env_vars.DUCKDNS_TOKEN, etc.

    - name: Pasar las variables cargadas a variables globales
      set_fact:
        k3s_install_token: "{{ env_vars.K3S_TOKEN }}"
        duckdns_token: "{{ env_vars.DUCKDNS_TOKEN }}"
        duckdns_domain: "{{ env_vars.DUCKDNS_DOMAIN }}"
        wifi_ssid: "{{ env_vars.WIFI_SSID }}"
        wifi_password: "{{ env_vars.WIFI_PASSWORD }}"
        letsencrypt_email: "{{ env_vars.LETSENCRYPT_EMAIL }}"

    # A partir de este punto, puedes llamar a tus roles usando esas variables:
  roles:
    - role: common
    - role: k3s
    - role: certmanager
