name: Build & Publish Dark Messiah Server

on:
  push:
    paths:
      - '.github/workflows/dark-messiah-docker.yml'
      - 'kubernetes/dedicated-servers/darkMessiah/DockerFile'
      - 'kubernetes/dedicated-servers/darkMessiah/start.sh'

jobs:
  detect-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Filter for both files changed
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            both:
              - 'kubernetes/dedicated-servers/darkMessiah/DockerFile'
              - 'kubernetes/dedicated-servers/darkMessiah/start.sh'

      - name: Skip if not both
        if: steps.filter.outputs.both != 'true'
        run: |
          echo "No changes in both Dockerfile and start.sh → skipping"
          exit 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./kubernetes/dedicated-servers/darkMessiah
          file: ./kubernetes/dedicated-servers/darkMessiah/DockerFile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:dark-messiah
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
